filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/server/req.log
    fields:
      topic: user-log

output.kafka:
  hosts: ["kafka:9092"]
  topic: 'log'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
